on: [push]

jobs:
  example:
    runs-on: ubuntu-22.04
    name: Test
    steps:
      - name: Default test
        uses: schemathesis/action@v1
        with:
          schema: test.json
          token: ${{ secrets.SCHEMATHESIS_TOKEN }}