on: [push]

jobs:
  example:
    runs-on: ubuntu-22.04
    name: Test
    steps:
      - name: Default test
        uses: ./
        with:
          schema: 'https://example.schemathesis.io/openapi.json'
          token: ${{ secrets.SCHEMATHESIS_TOKEN }}